version: '3.8'

services:
  web:
    build: .
    command: uvicorn config:app --host 0.0.0.0 --port 3000
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost:3000`)"
  traefik:
    image: traefik:v2.2
    ports:
      - 3000:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
